version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  commit-message:
    prefix: chore
    prefix-development: no-release
    include: scope
